services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    #Register rendering projects as service
    Mds\PimPrint\DemoBundle\Service\GettingStarted:
        parent: mds.pimprint.core.abstract_project #Rendering projects must use 'mds.pimprint.core.abstract_project' as parent
        public: true    #must be defined public
        autowire: true
        autoconfigure: false
    Mds\PimPrint\DemoBundle\Service\CommandDemo:
        parent: mds.pimprint.core.abstract_project
        public: true
        autowire: true
        autoconfigure: false
    Mds\PimPrint\DemoBundle\Service\DataPrintCarBrochure:
        parent: mds.pimprint.core.abstract_project
        public: true
        autowire: true
        autoconfigure: false
    Mds\PimPrint\DemoBundle\Service\DataPrintCarList:
        parent: mds.pimprint.core.abstract_project
        public: true
        autowire: true
        autoconfigure: false
    Mds\PimPrint\DemoBundle\Service\DataPrintAccessoryPartList:
        parent: mds.pimprint.core.abstract_project
        public: true
        autowire: true
        autoconfigure: false
    #Helper services
    Mds\PimPrint\DemoBundle\Service\DataPrintPublicationLoader: ~
