services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mds\PimPrint\DemoBundle\Service\:
        resource: '../../Service'

    Mds\PimPrint\DemoBundle\Project\DynamicPaginationDemo\:
        resource: '../../Project/DynamicPaginationDemo'

    Mds\PimPrint\DemoBundle\Project\LocalizationDemo\:
        resource: '../../Project/LocalizationDemo'

    Mds\PimPrint\DemoBundle\Project\CarsDemo\:
        resource: '../../Project/CarsDemo'
        exclude: '../../*/Dto/*'
