services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mds\PimPrint\DemoBundle\Service\:
        resource: '../src/Service'

    Mds\PimPrint\DemoBundle\Project\DynamicPaginationDemo\:
        resource: '../src/Project/DynamicPaginationDemo'

    Mds\PimPrint\DemoBundle\Project\LocalizationDemo\:
        resource: '../src/Project/LocalizationDemo'

    Mds\PimPrint\DemoBundle\Project\CarsDemo\:
        resource: '../src/Project/CarsDemo'
        exclude: '../src/*/Dto/*'
