imports:
    - { resource: getting-started.yaml }
    - { resource: pimprint.yaml }

doctrine_migrations:
    migrations_paths:
        'Mds\PimPrint\DemoBundle\Migrations': '@MdsPimPrintDemoBundle/src/Migrations'
