mds_pim_print_core:
    #    Optional locales to set in render mode to have floats converted to '.-strings'
    #    In demo we set a correct locale to assure that generation works on all server systems.
    #    This configuration is only needed on server systems where flaots are converted to ',-strings'
    lc_numeric: [ 'en_US.UTF-8', 'de_DE.UTF-8' ]
    #    host:
    #        hostname:
    #        protocol:
    #        port:
    #    Disable SVG Support when using InDesign prior CC 2020 (15.0)
    #    svg_support: false
    #    Set to false to use Asset modificationDate. Use if Storage returns wrong lastModified timestamp.
    #    file_storage_mtime: false
    projects:
        commandDemo:
            ident: 'commandDemo' #Use for multi Bundle or configuration implementations.
            name: 'Command Demo' #Name of project displayed in InDesign-Plugin.
            service: 'Mds\PimPrint\DemoBundle\Service\CommandDemo' #Service to use to render the project. Must inherit AbstractProject.
            create_update_layers: false
            template:
                default: 'PimPrint_CommandDemo.indd' #Default InDesign template filename.
            #            plugin_elements: #Available plugin elements.
            #                start_alignment: false #Field for start left/right page.
            #                page_bounds: false #Fields for page start/end.
            #                update_mode: true #Field for update modes.
            #                update_modes: [501, 502, 512] #Available update modes for project.
            assets:
                download: true #Toggles asset download.
                pre_download: false #Toggles asset download before rendering start.
        #                warnings_on_page: true #Toggles missing asset onPage warnings messages.
        #                thumbnail: 'product_detail_small' #Optional Pimcore thumbnail configuration for preview images.
        columnPagination:
            ident: 'columnPagination'
            name: 'Dynamic Column Pagination'
            service: 'Mds\PimPrint\DemoBundle\Project\DynamicPaginationDemo\ColumnPagination'
            template:
                default: 'PimPrint_CommandDemo.indd'
            assets:
                download: true
            plugin_elements:
                publications:
                    label: 'Manufacturer'
                update_modes: [ 501 ]
                start_alignment: true
        localizationDemo:
            ident: 'localizationDemo'
            name: 'Localization Demo'
            service: 'Mds\PimPrint\DemoBundle\Project\LocalizationDemo\LocalizationProject'
            template:
                default: 'PimPrint_CommandDemo.indd'
            assets:
                download: true
        carsDemoCarList:
            ident: 'carsDemoCarList'
            name: 'Car List'
            service: 'Mds\PimPrint\DemoBundle\Project\CarsDemo\CarList'
            template:
                default: 'PimPrint_CarsDemo_Template_pimcore.indd'
            assets:
                download: true
        carsDemoCarDetail:
            ident: 'carsDemoCarDetail'
            name: 'Car Detail'
            service: 'Mds\PimPrint\DemoBundle\Project\CarsDemo\CarDetail'
            template:
                default: 'PimPrint_CarsDemo_Template_pimcore.indd'
            assets:
                download: true
        carsDemoCarSalesLabel:
            ident: 'carsDemoCarSalesLabel'
            name: 'Car Sales Label'
            service: 'Mds\PimPrint\DemoBundle\Project\CarsDemo\CarSalesLabel'
            template:
                default: 'PimPrint_Cars_SalesLabel_pimcore.indd'
            assets:
                download: true
        carsDemoAccessoryList:
            ident: 'carsDemoAccessoryList'
            name: 'Accessory List'
            service: 'Mds\PimPrint\DemoBundle\Project\CarsDemo\AccessoryList'
            template:
                default: 'PimPrint_CarsDemo_Template_pimcore.indd'
            assets:
                download: true
        carsDemoAccessoryPriceList:
            ident: 'carsDemoAccessoryPriceList'
            name: 'Accessory Price List'
            service: 'Mds\PimPrint\DemoBundle\Project\CarsDemo\AccessoryPriceList'
            template:
                default: 'PimPrint_CarsDemo_Template_pimcore.indd'
            assets:
                download: true
